- app/controllers/application_controller.rb
- app/controllers/auth/devise_token_auth/sessions_controller.rb
- config/application.rb
- config/initializers/cors.rb
- config/routes.rb
> Complete devise token auth setup

- config/routes.rb
> Create custom PATCH route

- .pryrc
- app/models/match.rb
- app/models/prediction.rb
- db/migrate/20210415013709_add_round_to_matches.rb
- db/schema.rb
> Feature: Implement Match and Prediction instance methods

- Procfile
> Added procfile to auto migrate

- app/models/competition.rb
- app/models/leaderboard.rb
- app/models/membership.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20210421110232_change_leagues_to_leaderboards.rb
- db/schema.rb
- db/seeds.rb
> Leaderboard change

- config/initializers/devise_token_auth.rb
avoiding refresh of token in development
> avoiding refresh of token in development

- app/controllers/application_controller.rb
- app/controllers/v1/leaderboards_controller.rb
- app/controllers/v1/predictions_controller.rb
- app/models/leaderboard.rb
- app/policies/leaderboard_policy.rb
- app/views/v1/leaderboards/show.json.jbuilder
- config/initializers/active_record/secure_token.rb
- db/migrate/20210424101146_add_uniqueness_to_leagues.rb
- db/schema.rb
- test/controllers/v1/leaderboards_controller_test.rb
- test/policies/leaderboard_policy_test.rb
auto generate a unique token on league creation
> League create

- app/controllers/application_controller.rb
- config/environment.rb
Camelizing keys in the JSON rendered by the API since we are consuming the API in JavaScript.
> Camelize JSON keys in API rendering

- app/controllers/v1/leaderboards_controller.rb
- app/policies/leaderboard_policy.rb
> Leaderboards destroy

- app/views/v1/teams/_team.json.jbuilder
> Add `badge_url` to team partial

- config/initializers/cors.rb
Necessary fix for the setPrediction method in the FE.
> Add PATCH to CORS methods

- db/seeds.rb
Added more memberships to seeds
> Added more memberships

- app/models/competition.rb
- lib/tasks/competition.rake
Closes #45 
Duplicated the seeds to start tonight at 4am. Not the most elegant way of doing it but since it's a test, I didnt bother making it perfect. Plus it's super distracting in here.
⚠️ To run the task
```
rails competition:copy
```
> Competition test

- app/models/leaderboard.rb
previous wasn't behaving as intended
> give all users who have memberships and owner

- app/controllers/v1/competitions_controller.rb
- app/policies/competition_policy.rb
- app/views/v1/competitions/_competition.json.jbuilder
- app/views/v1/competitions/index.json.jbuilder
- app/views/v1/competitions/show.json.jbuilder
- config/routes.rb
Added a competitions index route, so that the FE can fetch them all and assign a default competition
> Add competitions#index

- lib/tasks/heroku.rake
> added a rake task to copy the production DB to development

- app/models/user.rb
still not ideal but better than current.
> scoping predictions by competition

- app/models/user.rb
> fixed score tally

- app/controllers/v1/matches_controller.rb
- app/controllers/v1/users_controller.rb
- app/policies/prediction_policy.rb
- app/policies/user_policy.rb
- app/views/v1/matches/index.json.jbuilder
- app/views/v1/users/_user.json.jbuilder
- app/views/v1/users/show.json.jbuilder
Made only predictions from other users for finished and ongoing games visible.
> Access past predictions from other users

- app/models/competition.rb
📢 @trouni this one is critical for tonight's games
> logic was backwards for on_going compeitions

- app/jobs/match_started_job.rb
- app/jobs/schedule_daily_tasks_job.rb
- test/jobs/match_started_job_test.rb
- test/jobs/schedule_daily_tasks_job_test.rb
Will set `ScheduleDailyTasksJob` to schedule updates for all of the matches that day
> added a daily job to check for day events

- lib/tasks/schedule.rake
> added the rake task to run the job

- app/models/round.rb
- app/models/user.rb
> increasing the score by 1 each round

- app/jobs/match_update_future_job.rb
- app/models/round.rb
- db/migrate/20210622083343_add_api_name_to_rounds.rb
- db/schema.rb
- db/seeds.rb
- lib/tasks/round.rake
Adding the final rounds so we can create matches
> Rounds create

- app/jobs/match_update_history_job.rb
- app/models/match.rb
- app/views/v1/predictions/_prediction.json.jbuilder
- db/migrate/20210705023732_add_more_scores_to_matches.rb
- db/schema.rb
Somehow this crashes the ruby interpreter for me... Could you give it a try?
> Add ET and PS scores logic

- app/controllers/v1/matches_controller.rb
- app/jobs/match_update_future_job.rb
- app/models/competition.rb
- db/migrate/20221108131452_add_api_id_to_groups.rb
- db/schema.rb
- lib/tasks/competition.rake
- lib/tasks/team.rake
Created a rake task to setup the World Cup groups and teams. 
No matches yet. Need an API for that.
> World cup setup

- Gemfile
- Gemfile.lock
Sorry @trouni im going to merge this as a last test bc i think i got it working
> downgraded sidekiq and redis

- app/models/user.rb
- app/views/v1/users/show.json.jbuilder
> passing possible points to the user

- app/jobs/schedule_daily_tasks_job.rb
We're calling it every 10minutes now.
> removed unnecessary match updating

- app/models/competition.rb
Embarrassingly added something yesterday without testing it. Now a competition has many users
> competition has many users

- app/jobs/match_update_history_job.rb
- app/jobs/match_update_live_job.rb
- app/models/match.rb
- app/services/live_score_api.rb
- db/live_score_example.json
- lib/tasks/competition.rake
- test/jobs/match_update_live_job_test.rb
Used the live scores api endpoint to update the scores during the game. plus refactored the history job to share the logic.
> Calling API to update the scores LIVE

- lib/tasks/round.rake
⚠️ This needs to be run ASAP so that users can predict the new games
```
heroku run rails round:create_all
```
> updated round creation for the world cup"

- app/jobs/match_update_future_job.rb
- app/models/match.rb
this prevents duplicates. however.... ⚠️ 
the API has been sending the "correct" match 2nd. So as of right now, it would make the correct match fail. but it's a start and I'm too hungry to think about how to go about that one.
> prevents duplicate games on the same day

- app/jobs/competition_create_job.rb
- test/jobs/competition_create_job_test.rb
You'll need the right API key for access to Copa America
To run the job (with Sidekiq open):
```
CompetitionCreateJob.perform_now('CA')
```
> added copa america
